package pes00038.cs.stir.ac.uk.dissertation;

import pes00038.cs.stir.ac.uk.dissertation.CrossoverOperators.*;
import pes00038.cs.stir.ac.uk.dissertation.MutationOperators.*;
import pes00038.cs.stir.ac.uk.dissertation.SelectionOperators.*;


public class Settings {

	public static final String DATASET_PATH = "/Users/Petter/Desktop/University of Stirling/Year 4/Project/Datasets/6.in";
	public final static int TIME_TO_RUN = 5; //Time to run in seconds
	
	//Operators to use; see CrossoverOperators, MutationOperators, and SelectionOperators packages
	public final static Crossover CROSSOVER_TO_USE = new OneRepairCross();
	public final static Mutation MUTATION_TO_USE = new AdaptiveMutationSet();
	public final static Selection SELECTION_TO_USE = new SimulatedAnnealingSelectionStricter();
	
	//Size of population to use
	public final static int POPULATION_SIZE = 50;
	
	//Whether or not to mutate child generated by crossover
	public final static boolean MUTATE_CHILD = true;
	
	//Minimum (inclusive) and maximum (inclusive) number of mutations per iteration
	public final static int MINIMUM_MUTATIONS = 1;
	public final static int MAXIMUM_MUTATIONS = 2;
	
	//Enable detailed debug write and specify path
	public final static boolean COLLECT_DEBUG = false;
	public final static String DEBUG_PATH = "/Users/Petter/Desktop/DissertationOutput/";
	
	//How many times to run GA in automatic mode
	public final static int AUTOMATIC_MODE_RUNS = 30;
	
}
